### ISSUE TITLE
Github workflows using deprecated actions

### ISSUE THREAD

**Issue by jasonhebert** [aeon-php/actions#1]
**Describe the bug**
The workflow files reference deprecated workflow actions `actions/cache@v2` and `actions/checkout@v2` causing failures in projects using this repo.

**Expected behavior**
Update workflow actions to v3 or v4 per GitHub documentation:
https://github.blog/changelog/2024-09-16-notice-of-upcoming-deprecations-and-changes-in-github-actions-services/
https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/

**Additional context**

**Comment by norberttech** [comment]
Actions are now updated, thanks for reporting!
